name: Cypress Tests
on:
  workflow_call:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'oracle' # See https://github.com/marketplace/actions/setup-java-jdk#supported-distributions for available options
          java-version: '25'
      - name: Ensure java 21+ is installed
        run: |
          # Adapated from https://www.javathinking.com/blog/correct-way-to-check-java-version-from-bash-script

          # This SO was useful for figuring out how to write the regex correctly inline:
          # https://stackoverflow.com/questions/13150411/why-does-bash-rematch-not-work-for-a-quoted-regular-expression

          if [[ "$(java --version)" =~ [[:space:]]([[:digit:]]+)\. ]]; then
          # if [[ "openjdk 17" =~ [[:space:]]([[:digit:]]+)\.? ]]; then # Uncomment to test that it fails on lower versions
            JAVA_VERSION="${BASH_REMATCH[1]}"
            JAVA_VERSION="${JAVA_VERSION:-0}"
            echo "Got java version $JAVA_VERSION"
            if [[ $JAVA_VERSION -lt "21" ]]; then
              echo "...but needed java 21+"
              exit 1
            fi
          fi
      # Install firebase emulators
      - run: npm install -g firebase-tools
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        env:
          DEBUG: '@cypress/github-action' # Turn on debug logs for troubleshooting
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          # Wait for the emulator UI to be available (indicates emulators fully loaded)
          # and for the page to be available on the hosting emulator.
          wait-on: 'http://localhost:4000, http://localhost:5002'
          build: 'npm run build:tests'
          start: npm run emulators:tests
          record: false